### ISSUE TITLE
Can't open photopea (windows 10)

### ISSUE THREAD

**Issue by tarekelassady** [DUOLabs333/photopea#12]
Hello, As per your guide, I opened command (cmd) and opened the folder when I installed the photopea-main zip folder. Then I typed ./.photopea, but the command prompt refused, then I typed ./.photopea, it has been accepted, but when I type localhost:8080 in chrome or other browsers, I got the message "This site can’t be reached" ERR_CONNECTION_REFUSED...
Please help me to solve it.
Thanks
Tarek

**Comment by DUOLabs333** [comment]
Oh, I am so sorry. The default port is `8002` now. I'll update that soon.

**Comment by DUOLabs333** [comment]
Fixed in latest commit.
