### ISSUE TITLE
Photopea: Some issues don't work

### ISSUE THREAD

**Issue by tarekelassady** [DUOLabs333/photopea#13]
1- At the beginning, the "Loading" message appears, but never disappeared again
2- I can't edit text layers
3- I can't add text

Please your help to solve these problems and put smiles on our faces as usual
Thank You
Tarek

**Comment by DUOLabs333** [comment]
Are you running it from the launcher?

**Comment by tarekelassady** [comment]
I don't understand. I just run it from Chrome and brave
I opened index.html from the local file of the program

![Untitled](https://user-images.githubusercontent.com/94428272/142085264-437ead06-3b10-4bda-a16c-e2cae38492da.png)

**Comment by DUOLabs333** [comment]
That's your problem. Run `./.photopea` and open up `localhost:8002`

**Comment by tarekelassady** [comment]
I opened cmd and then cd to the program folder and typed ./.photopea 
I go the message: '.' is not recognized as an internal or external command,
operable program or batch file.
Then I typed ".photopea", it asked me with which program to run with, I opened Chrome and typed localhost:8002, but, I got the message "This site can’t be reached".
!!!

**Comment by tarekelassady** [comment]
Then, I don't know how to run ./.photopea

**Comment by DUOLabs333** [comment]
Right, you're on Windows. Do you have python installed?

**Comment by tarekelassady** [comment]
yeah I have Python 3.10
![image](https://user-images.githubusercontent.com/94428272/142136467-fc9dc1dc-c758-4524-8f3f-c460b4826369.png)

**Comment by DUOLabs333** [comment]
So on the command prompt you can type `python` and it will give you a REPL?

**Comment by tarekelassady** [comment]
It opens Microsoft store with Python 3.9
![image](https://user-images.githubusercontent.com/94428272/142136998-9a727d21-341a-446b-b8b8-85838fb17535.png)

**Comment by DUOLabs333** [comment]
That's why -- you have to make sure the folder where python is the first in the $PATH.

**Comment by tarekelassady** [comment]
I'm not a developer sir. I don't understand , I just follow steps. 
I wrote python, then?

**Comment by DUOLabs333** [comment]
Ok, so first you want to go to Control Panel, then search for Environment Variables. You will get a list. Choose to edit the local variables, then choose PATH from there. Add the folder to the very top of the list. Add a screenshot if you're lost at any point.

**Comment by tarekelassady** [comment]
![image](https://user-images.githubusercontent.com/94428272/142137910-c42411dd-5324-4bdc-a21d-403147666451.png)

**Comment by tarekelassady** [comment]
Isn't there something easier to run your program, because really, I like it
![image](https://user-images.githubusercontent.com/94428272/142137998-c45b2fc7-14b7-45e1-bb60-fa9a404b39b5.png)

Well. Anyway, then?

**Comment by NFXT** [comment]
> Isn't there something easier to run your program, because really, I like it ![image](https://user-images.githubusercontent.com/94428272/142137998-c45b2fc7-14b7-45e1-bb60-fa9a404b39b5.png)
> 
> Well. Anyway, then?

why do you even have python installed if you don't know how to use it? 🙄
if I have time later today, I'll build a standalone electron app so that you can run it directly with no issues

**Comment by tarekelassady** [comment]
Really thank you Sir, that's amazing to build a standalone app
I installed Python, because I googled how can I run executable python software on windows 10, and I've read that I need to install Python first, then, I couldn't do anything of any instructions 😄
But, really, anyway if you make this windows executable, it will be amazing and complete solution for your clients and followers

**Comment by NFXT** [comment]
> Really thank you Sir, that's amazing to build a standalone app I installed Python, because I googled how can I run executable python software on windows 10, and I've read that I need to install Python first, then, I couldn't do anything of any instructions 😄 But, really, anyway if you make this windows executable, it will be amazing and complete solution for your clients and followers

it's not our app to be honest, @DUOLabs333 ported it so that it can be used completely offline

**Comment by NFXT** [comment]
@tarekelassady It's done. Check it out: https://github.com/NFXT/Photopea-Desktop-App

**Comment by DUOLabs333** [comment]
@NFXT I don't particularly like Electron, but if it works, great (someone else was working on a port to Electron). @tarekelassady Just a note -- since this a client-side static site, it can work with any server software: NGINX, Apache, Caddy, etc.

**Comment by DUOLabs333** [comment]
Can you post the source code for the app?

**Comment by NFXT** [comment]
> Can you post the source code for the app?

Sure, I'll post it tomorrow
I also fixed the import from URL by injecting custom code..I coded a validator along with error messages, whether the URL is valid, the request was successful, the image is valid etc..I haven't included it in the electron app tho..I kept it untouched..also for the texts and fonts to work I had to refrain from using ASAR..so the src code is completely exposed and can be edited directly without re packaging the desktop app..but yea I'll post everything tomorrow

**Comment by tarekelassady** [comment]
> @tarekelassady It's done. Check it out: https://github.com/NFXT/Photopea-Desktop-App

Really you are amazing @NFXT ... I like you work. It work perfectly 👍
Thank you @DUOLabs333 & @NFXT for you effective and really great support.
I will always follow your work. It's amazing.

My best regards and further of success 
Thank you
Tarek

**Comment by tarekelassady** [comment]
Really good job, but @NFXT when I try to add text or sometimes to edit text, "Loading' label appears and never gone and I can't add text layer
![image](https://user-images.githubusercontent.com/94428272/142388099-d1e3839f-5b8f-402e-9363-ff4562b2e197.png)

**Comment by NFXT** [comment]
1

> Really good job, but @NFXT when I try to add text or sometimes to edit text, "Loading' label appears and never gone and I can't add text layer ![image](https://user-images.githubusercontent.com/94428272/142388099-d1e3839f-5b8f-402e-9363-ff4562b2e197.png)

That's because I haven't included all the fonts, and you are trying to use a font that does not exist, hence why it's throwing this error, to include all the fonts, download the full folder (It's around 1.5 gb or so) from DUOLabs333's, and copy paste the "fonts" folder from DUOLabs333's and replace it in the folder of the desktop app I made. (www.photopea.com > rsrc > fonts)

**Comment by NFXT** [comment]
@tarekelassady I uploaded the full version, so you can just download and run, the al fonts should work now. 
@DUOLabs333 I added the src code for the app as well.

**Comment by DUOLabs333** [comment]
So how do you compile it?

**Comment by NFXT** [comment]
> So how do you compile it?

I used electron-packager..there are other libraries for distribution as well like electron-builder

**Comment by NFXT** [comment]
install node js, install the library (electron-packager) in the local folder (the website says global installation is not recommended) and open the folder in terminal and run npx command..everything is detailed on their GitHub page

**Comment by tarekelassady** [comment]
> 1
> 
> > Really good job, but @NFXT when I try to add text or sometimes to edit text, "Loading' label appears and never gone and I can't add text layer ![image](https://user-images.githubusercontent.com/94428272/142388099-d1e3839f-5b8f-402e-9363-ff4562b2e197.png)
> 
> That's because I haven't included all the fonts, and you are trying to use a font that does not exist, hence why it's throwing this error, to include all the fonts, download the full folder (It's around 1.5 gb or so) from DUOLabs333's, and copy paste the "fonts" folder from DUOLabs333's and replace it in the folder of the desktop app I made. ([www.photopea.com](http://www.photopea.com) > rsrc > fonts)

Really

**Comment by tarekelassady** [comment]
> 1
> 
> > Really good job, but @NFXT when I try to add text or sometimes to edit text, "Loading' label appears and never gone and I can't add text layer ![image](https://user-images.githubusercontent.com/94428272/142388099-d1e3839f-5b8f-402e-9363-ff4562b2e197.png)
> 
> That's because I haven't included all the fonts, and you are trying to use a font that does not exist, hence why it's throwing this error, to include all the fonts, download the full folder (It's around 1.5 gb or so) from DUOLabs333's, and copy paste the "fonts" folder from DUOLabs333's and replace it in the folder of the desktop app I made. ([www.photopea.com](http://www.photopea.com) > rsrc > fonts)

Really you are wonder @NFXT .. Thank you for your support and your big effort )))

**Comment by tarekelassady** [comment]
> 

Really you are wonderful @NFXT .. Thank you for your support and your big effort )))

**Comment by tarekelassady** [comment]
> 1
> 
> > Really good job, but @NFXT when I try to add text or sometimes to edit text, "Loading' label appears and never gone and I can't add text layer ![image](https://user-images.githubusercontent.com/94428272/142388099-d1e3839f-5b8f-402e-9363-ff4562b2e197.png)
> 
> That's because I haven't included all the fonts, and you are trying to use a font that does not exist, hence why it's throwing this error, to include all the fonts, download the full folder (It's around 1.5 gb or so) from DUOLabs333's, and copy paste the "fonts" folder from DUOLabs333's and replace it in the folder of the desktop app I made. ([www.photopea.com](http://www.photopea.com) > rsrc > fonts)

Really you are wonderful @NFXT .. Thank you for your support and your big effort )))
