### ISSUE TITLE
Photopea electron wrapper

### ISSUE THREAD

**Issue by tim0-12432** [DUOLabs333/photopea#14]
Hi,
I really like your idea. ❤️ 
I just wanted to point at my fork of your project. There I created a basic electron wrapper for the offline files and a github workflow to build the certain programs.
Unfortunately I didn't discover NFXT working on something similar till yesterday.
If you would like to merge my version into your project, I will create a PR of course.
Your functionalities work as before and expected.
![image](https://user-images.githubusercontent.com/79634593/142613002-62f8d239-e0cc-4007-9e72-aa68e5bc9616.png)
![image](https://user-images.githubusercontent.com/79634593/142613275-8c4a8c3d-9aa0-46c7-ac6c-fbf37b5a0aab.png)
![image](https://user-images.githubusercontent.com/79634593/142613918-3f24780f-8a31-48f8-9eb2-3f5d79209f62.png)
Regards,
Timo

**Comment by DUOLabs333** [comment]
Yeah, I saw it in my home page. Nice! I don't particularly like Electron though, but it seems that multiple people want it, so I'll put a link to both of yours' in the README.

**Comment by tim0-12432** [comment]
Okay that's fine. Electron is the easiest way to put the scraped files into a desktop app I think.

**Comment by NFXT** [comment]
Good job @tim0-12432 I only built the app after some guy was having issues with the web app as he had to run it in a server, and it's kinda overwhelming for a beginner.
Also, @DUOLabs333 you didn't link the proper repo..this is the one: https://github.com/NFXT/Photopea-Desktop-App

**Comment by DUOLabs333** [comment]
Sorry, @NFXT, fixed.
