### ISSUE TITLE
missing custom shapes

### ISSUE THREAD

**Issue by omrahm** [DUOLabs333/photopea#17]
all of the custom shapes are missing (except for the play button)

offline version:
![image](https://user-images.githubusercontent.com/77696938/152989145-15d150ed-51da-4cbe-91b1-dcca23d32e26.png)

online version:
![image](https://user-images.githubusercontent.com/77696938/152989426-9f0f7a9b-bda9-4b5e-945e-7a9c6520c2f2.png)

**Comment by DUOLabs333** [comment]
Can you list the steps to reproduce?

**Comment by DUOLabs333** [comment]
Ok, found the problem -- there's yet another file it loads. I'm pushing out a fix.

**Comment by DUOLabs333** [comment]
Fixed with recent commit fed5df8.
