### ISSUE TITLE
How is this offline?

### ISSUE THREAD

**Issue by CHJ85** [DUOLabs333/photopea#18]
This is not really offline.
This script only forwards the Photopea website to your local server. Right?

**Comment by DUOLabs333** [comment]
No, it loads a local copy of Photopea from your computer.

**Comment by CHJ85** [comment]
But looking at the script, it looks like it's forwarding the photopea website to localhost:8080
python -m http.server --directory www.photopea.com 8080
Or am I wrong? Sorry if I'm wrong.

**Comment by CHJ85** [comment]
Oh nevermind. I was wrong. It's forwarding the directory. And now looking at he code, I can see that it's the downloaded site.
I'm sorry.
